### ISSUE TITLE
Compose fails with error message 

### ISSUE THREAD

**Issue by 3M-PELTOR** [frzb/coinboot#12]
used a fresh cloned vanilla version of the coinboot master and try to do a 

`docker-compose up `
and it failed with the linked error message 

```
Building coinboot
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 952, in up
    start=not no_start
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 431, in up
    svc.ensure_image_exists(do_build=do_build)
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 318, in ensure_image_exists
    self.build()
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 923, in build
    shmsize=parse_bytes(build_opts.get('shm_size')) if build_opts.get('shm_size') else None,
TypeError: build() got an unexpected keyword argument 'stream'
```

**Comment by 3M-PELTOR** [comment]
Fixed the Issue with the latest release of docker-compose 1.23 
[docker-compose website](https://docs.docker.com/compose/install/#prerequisites
)
getting the new package

`sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
`
setting it executable

`sudo chmod +x /usr/local/bin/docker-compose`

beware to uninstall the docker-compose of the ubuntu repository

`sudo apt remove docker-compose`

**Comment by frzb** [comment]
@3M-PELTOR  Thank you for giving Coinboot a try and reporting this behavior.

So we should add Docker Compose => 1.23 as requirement?

PS: Be  aware that Coinboot is still in beta state. So it may turn up into flames immediately . 
 If you face any issue don't hesitate to get in contact with me!

**Comment by 3M-PELTOR** [comment]
a requirement in Docker Compose would minimize further problems
